name: SuperVanish
main: de.myzelyam.supervanish.SuperVanish
author: MyzelYam
description: Advanced /vanish plugin which makes other players think that you're not on the server
version: 5.9.3
website: https://www.spigotmc.org/resources/supervanish-be-invisible.1331/
softdepend:
- ProtocolLib
- LibsDisguises
- DisguiseCraft
- dynmap
- Essentials
- TrailGUI
- Citizens
- SuperTrails
commands:
  sv:
    usage: /sv
    description: SuperVanish's main command
    aliases: [v, supervanish, vanish, vlist]
  vlogin:
    usage: /vlogin
    description: Broadcasts a login-message
    aliases: [svlogin]
  vlogout:
    usage: /vlogout
    description: Broadcasts a logout-message
    aliases: [svlogout]
permissions:
  sv.*:
    children:
    - sv.use
    - sv.see
    - sv.reload
    - sv.login
    - sv.logout
    - sv.others
    - sv.list
    - sv.fly
    - sv.toggleitempickups
    - sv.updatecfg
  supervanish.*:
    children:
    - sv.use
    - sv.see
    - sv.reload
    - sv.logout
    - sv.login
    - sv.others
    - sv.list
    - sv.fly
    - sv.toggleitempickups
    - sv.updatecfg